version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Download packer
          command: |
            wget -q https://releases.hashicorp.com/packer/1.3.4/packer_1.3.4_linux_amd64.zip
            unzip packer*.zip
            chmod +x packer
      - run:
          name: Build AMI
          command: |
            ./packer build \
            -var "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" \
            -var "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" \
            -var "aws_region=${aws_region}" \
            -var "subnet_id=${subnet_id}" \
            -var "source_ami=${source_ami}" \
            -var "ssh_username=${ssh_username}" \
            -var "REGION_IDENTIFIER=${REGION_IDENTIFIER}" \
            centos-ami.json